name: Let's go!

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
        - '1.21.x'
        - '1.22.x'
        - '1.23.x'
        - '1.24.x'

    name: Go ${{ matrix.go-version }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v -o ./bin/keybon ./cmd

    - name: Test
      run: go test -v -json ./... > TestResults-${{ matrix.go-version }}.json

    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json
